version: '3.8'

# Standalone Redis deployment for distributed caching
# Can be used independently or with the main docker-compose files

services:
  redis:
    image: redis:7-alpine
    container_name: llmguard-redis
    hostname: redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory ${REDIS_MAX_MEMORY:-512mb}
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
      --loglevel ${REDIS_LOG_LEVEL:-warning}
      --requirepass ${REDIS_PASSWORD:-}
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    environment:
      - TZ=UTC
    restart: unless-stopped
    networks:
      - redis_network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Redis Commander - Web UI for Redis (optional, for development)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: llmguard-redis-commander
    hostname: redis-commander
    ports:
      - "${REDIS_COMMANDER_PORT:-8081}:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379:0:${REDIS_PASSWORD:-}
      - HTTP_USER=${REDIS_COMMANDER_USER:-admin}
      - HTTP_PASSWORD=${REDIS_COMMANDER_PASSWORD:-admin}
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - redis_network
    profiles:
      - dev  # Only start with: docker-compose --profile dev up

volumes:
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${REDIS_DATA_DIR:-./data/redis}

networks:
  redis_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
