services:
  minio-master:
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z
    container_name: minio-master
    hostname: minio-master
    ports:
      - "127.0.0.1:9000:9000"   # API
      - "127.0.0.1:9002:9001"   # Console / dashboard
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-miniopassword}
    volumes:
      - ./data-master:/data
    extra_hosts:
      - "minio-slave1:192.168.1.19"   # replace with actual slave IP
    command: server --console-address ":9001" http://minio-master:9000/data http://minio-slave1:9000/data  
    restart: unless-stopped
    networks:
      - minio_net

networks:
  minio_net:
    driver: bridge