services:
  minio-slave1:
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z
    container_name: minio-slave1
    hostname: minio-slave1
    ports:
      - "127.0.0.1:9000:9000"   # API
      - "127.0.0.1:9001:9001"   # Console / dashboard
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-miniopassword}
    volumes:
      - ./data-slave1:/data
    extra_hosts:
      - "minio-master:192.168.1.17"   # replace with master IP
    command: server --console-address ":9001" http://minio-master:9000/data http://minio-slave1:9000/data
    restart: unless-stopped
    networks:
      - minio_net

networks:
  minio_net:
    driver: bridge