version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: ollama-redis
    hostname: redis
    ports:
      - "127.0.0.1:6379:6379"  # Only accessible from localhost
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - ollama_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    hostname: ollama
    ports:
      - "127.0.0.1:11434:11434"  # Only accessible from localhost by default
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - ollama_network

  ollama-guard-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ollama-guard-proxy
    hostname: ollama-guard-proxy
    ports:
      - "8080:8080"  # Proxy API endpoint
    environment:
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_PATH=/api/generate
      - PROXY_HOST=0.0.0.0
      - PROXY_PORT=8080
      - ENABLE_INPUT_GUARD=true
      - ENABLE_OUTPUT_GUARD=true
      - ENABLE_IP_FILTER=false
      # Whitelist example: "192.168.0.0/16,10.0.0.0/8"
      - IP_WHITELIST=
      # Blacklist example: "192.168.1.100,10.0.0.5"
      - IP_BLACKLIST=
      - BLOCK_ON_GUARD_ERROR=false
      - CONFIG_FILE=/app/config.yaml
      # Redis cache configuration
      - CACHE_ENABLED=true
      - CACHE_BACKEND=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - CACHE_TTL=3600
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
      ollama:
        condition: service_started
    restart: unless-stopped
    networks:
      - ollama_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  ollama_data:
    driver: local
  redis_data:
    driver: local

networks:
  ollama_network:
    driver: bridge
